### ISSUE TITLE
Update tests to use `unixhierarchysep`and `altnamespace`.

### ISSUE THREAD

**Issue by ajaysusarla** [cyrusimap/cassandane#25]
Currently, with the Cassandane tests, we need to explicitly set `altnamespace` and `unixhierarchysep` to no (either in the `imapd.conf` or `cassandane.ini`(under the `[config]` section):
```
altnamespace = no
unixhierarchysep = no
```
We need to update tests both the `unixhierarchysep` and `altnamespace`.

**Comment by nicolan** [comment]
Well, ideally we want to have the tests to expect the altnamespace/unixhierarchysep to be yes because that's the new defaults for Cyrus master.

Or, if they're explicitly specified, obey their yes/no setting.

**Comment by ajaysusarla** [comment]
@nicolan ack! @brong has offered to help me with this, so i guess this is as good as fixed! :)

**Comment by nicolan** [comment]
Also: please update cassandane.ini.example to reflect the values appropriately. (Possibly have two sets: one with a note for 2.4/2.5 saying that product line defaults to altnamespace/unixhierarchysep being off, and one for 3.0 saying cyrus defaults to them being on)

**Comment by elliefm** [comment]
fyi, we already have #13 open about this ;)

**Comment by ajaysusarla** [comment]
Thanks for pointing that out @elliefm - will mark this as a duplicate of #13 and close.
