### ISSUE TITLE
Adjust doc/setting_up.txt for current cyrus imap

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cassandane#74]
doc/setting_up.txt recommends
```
    Your Cyrus install needs to have this patch applied, which
    allows Cyrus to be started as the Cyrus user instead of being
    started as root and changing to the Cyrus user.

    http://git.cyrusimap.org/cyrus-imapd/commit/?id=a5caf503c7060b4f1ec546e4dc6fe75e5b9c4029

    This patch has been in the CMU master development branch for
    some time, but not in any of the release branches.

```
but `git cherry-pick a5caf503c7060b4f1ec546` does not apply towards the master branch.

**Comment by elliefm** [comment]
I think that information is very old/wrong, we don't need to patch Cyrus to run Cassandane

**Comment by elliefm** [comment]
Even 2.5 can run in cassandane without extra patches... I guess this was old 2.4 or earlier information?

**Comment by elliefm** [comment]
I've updated the file to remove the reference to the patch, and tweaked a couple of other details that have changed over time
