### ISSUE TITLE
Not clear how to set cassadane.ini:[caldavtalk]:basedir

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cassandane#76]
doc/README.deps states:
```
 * Mail::JMAPTalk
 * Net::DAVTalk
 * Net::CalDAVTalk
 * Net::CardDAVTalk

    These are all packages built by FastMail and available in git for now
    while we nail down the APIs, sorry.  You'll have to pull them from:

    https://github.com/brong/Mail-JMAPTalk
    https://github.com/brong/Net-DAVTalk
    https://github.com/brong/Net-CalDAVTalk
    https://github.com/brong/Net-CardDAVTalk
```
and in cassadane.ini.example:
```
# This section describes how Cassandane interacts with the Net::CalDAVTalk
# module.  If the basedir is set, we can test the built in API tests against
# cyrus's CalDAV support for event+json
[caldavtalk]
# The base directory of a copy of Net::CalDAVTalk from CPAN.  If empty,
# the cpan tests won't be run
##basedir =

```
The first snippet says, Net::CalDAVTalk is not on CPAN and the second snippet states the opposite.

Besides, for me it is not clear, where basedir shall point to, once "make install" is called within Net-CalDAVTalk/

What does “cyrus's CalDAV support for event+json” mean?

**Comment by elliefm** [comment]
I also don't know how to configure this... [investigates]

Ahh, so these tests are in Cassandane/Cyrus/Caldav.pm and are called `test_netcaldavtalktests_fromical` and `test_netcaldavtalktests_fromje`.  Looking at them, the `caldavtalk.basedir` should be the Net::CalDAVTalk source directory (which contains the "testdata" directory).  

It looks like the CPAN package doesn't contain the testdata directory, so you would need to use a clone of the git repository, and set its path as the basedir.  It's fine to use the version from CPAN generally, you only need the git clone specifically for this testdata directory.

I've just tried setting it up myself (with Cyrus master), ``test_netcaldavtalktests_fromical` fails and `test_netcaldavtalktests_fromje` errors.  The testdata files were last updated in 2016 so I guess maybe they're out of date?

I don't know what "event+json" means, but maybe it's an old name for what's currently the jscalendar ietf draft?

**Comment by elliefm** [comment]
I've updated README.deps and cassandane.ini.example, and will keep these in my regular testing routine
